### ISSUE TITLE
navigator.notification.alert does not work in iOS

### ISSUE THREAD

**Issue by ryuheimat** [apache/cordova-plugin-dialogs#106]
navigator.notification.alert works fine in android but not work at ios.

**Comment by brodybits** [comment]
Demo project would be really helpful.

<https://github.com/brodybits/cordova-dialogs-bootstrap-test> shows this plugin working on iOS, Android, and Windows.

**Comment by jcesarmobile** [comment]
Yeah, can't reproduce.
Please, next time provide:
cordova cli version
cordova platform version
OS version of the device/simulator you tested it on

Bonus points for a sample project or steps to reproduce with sample code
