### ISSUE TITLE
Title is cut off for long titles on android

### ISSUE THREAD

**Issue by khaledosman** [apache/cordova-plugin-dialogs#108]
I have a function that is using the plugin as follows:

```
navigator.notification.alert(
      message, // message
      () => {}, // callback
      header, // title
      'Ok' // buttonName
    )
```
This works fine on iOS, however on Android when the header is big it doesn't split the text in new lines and shows '...' instead, I tried manually adding '\n' in the string, but its still showing ... instead of the full header message.

**Comment by hazems** [comment]
Currently, In Android, we just use the native Android Alert dialog's title property (which limit number of displayed lines to only two). We're not setting a custom textview, so we can't change the number of lines.

From a user experience point of view, I think more than 2 lines for a title seems really unfriendly. So why not setting this lengthy text in the message?

@macdonst @jcesarmobile @purplecabbage What do you think, Do we have any plans to add custom textviews to handle very big titles?

**Comment by purplecabbage** [comment]
No plans. 
It would be good to document the available length though.

**Comment by hazems** [comment]
Sure, will update documentation, thanks @purplecabbage.

**Comment by hazems** [comment]
@purplecabbage Documentation update PR is available: 
https://github.com/apache/cordova-plugin-dialogs/pull/125

**Comment by janpio** [comment]
This is now documented in README.
