### ISSUE TITLE
Use UIAlertController instead of UIAlertView on iOS

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-plugin-dialogs#119]
since UIAlertView is deprecated

found a possible solution in: <https://stackoverflow.com/questions/32690086/uialertview-first-deprecated-ios-9>

**Comment by jcesarmobile** [comment]
The plugin already uses UIAlertController, but for iOS 8 and newer, we can safely remove the old code that uses UIAlertView as iOS 7 and older are not supported, but probably needs a major release.
