### ISSUE TITLE
Prompt don't close until callback?

### ISSUE THREAD

**Issue by joe-scotto** [apache/cordova-plugin-dialogs#126]
Is there a way with the `prompt()` method to not close it until a function completes? 

For example, I'm using the following to prompt a user for their password to confirm account changes, upon successful password it should just show an alert but if the password is incorrect it should leave the prompt open for them to attempt it again. 

```
this.dialogs.prompt(
      'Enter your password please', 
      'Password',
      [
        'Close',
        'OK'
      ]
    )
```

It seems that no matter what, the buttons always close the prompt, they have no option to leave it open.

**Comment by jcesarmobile** [comment]
no, it's not possible, you should call the prompt again if it's not right
