### ISSUE TITLE
Wy isn't feature (GH-128), aka dialog dismissal, included in latest release

### ISSUE THREAD

**Issue by tymcdowell** [apache/cordova-plugin-dialogs#159]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
This change is almost 2 years old and is only on the master branch.  Any chance it is getting added to a release anytime soon?

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Because latest release is prior to that PR being merged, so will be included in next release.
In the meantime you can install the plugin from GitHub
