### ISSUE TITLE
'UIAlertView' is deprecated when installing cordova-plugin-dialogs

### ISSUE THREAD

**Issue by TraktorBengan** [apache/cordova-plugin-dialogs#161]
Hi!

I'm having issues installing Cordova-plugin-dialogs to use for my project.
This plugin: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-dialogs/index.html
Installing works fine without issues but when I build it, I get 7 fault codes all related to the 'UIAlertView' is deprecated.
I do not know how to fix this even though this has been replaced dby some UIAlertController?

![Skärmavbild 2022-05-18 kl  23 57 41](https://user-images.githubusercontent.com/105824618/169162657-4376526b-b002-4754-9df4-14649a233e5c.png)

I have checked a tons of tickets regarding this, removed my ios platforms, started a new project fresh from start etc etc etc.
I really have no clue of how to fix this issue.

Please help me

**Comment by TraktorBengan** [comment]
Bump, please help me

**Comment by breautek** [comment]
A deprecation just means that the code is no longer supported by the maintainer for the reason or another.

Commonly Cordova has no choice but to use older deprecated methods in order to maintain support for older devices, so generally speaking, deprecation warnings can safely be ignored as long as it's not introducing runtime issues.

In this particular case however, the replacement [UIAlertController](https://developer.apple.com/documentation/uikit/uialertcontroller) has been implemented in the SDK since iOS 8 so this code could be migrated to use the new alert classes.

**Comment by TraktorBengan** [comment]
Thank you breatuek!

Do you know how I can continue?
The plugin does not work even though you said it might. I do not have the knowledge to change to using the UIAlertController instead.

Any tips or ideas?
Thank you so much.

**Comment by breautek** [comment]
> The plugin does not work even though you said it might. 

What about it doesn't work? We will need to know what you expect the plugin to do and what the plugin is actually doing.

**Comment by TraktorBengan** [comment]
The plugin should allow me to create a promt or notification that pops up on the screen. In my case i want to press a button, then it should make a popup with some information and then press ok to continue. 

The plug-in does not seem to work. You mentioned in a good scenario these errors could be ignored but I’m guessing the plug-in isn’t working due to the error message.

**Comment by TraktorBengan** [comment]
I have followed this guide to install it etc: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-dialogs/index.html

I am also trying to use this example below exactly in my code.

`function alertDismissed() {
    // do something
}

navigator.notification.alert(
    'You are the winner!',  // message
    alertDismissed,         // callback
    'Game Over',            // title
    'Done'                  // buttonName
);`

**Comment by TraktorBengan** [comment]
Wow, Thank you breautek!

I really appreciate you spending your time helping me. I honestly have no clue if I use the device ready event. If I recall correctly, I have never used this, I most likely removed all code from when creating the app and never heard about this event either.

Like I said, huge thank you. I will try this later today, have a wonderful day.

**Comment by breautek** [comment]
Error indicates that it is failing to parse the `config.xml` file. It's impossible for me to give any actual advice with no real information provided. Best I can do is ensure you have a well formed XML file.

I'm closing this issue as it seems like the original issue has been sorted out. Yes, the codebase contains deprecated code, no, that doesn't necessarily indicate a bug. To summarize, the `deviceready` event needs to be fired before calling on any cordova plugin APIs.

If you believe you have found a bug within the cordova codebase, please file a new issue with the issue form filled out.
