### ISSUE TITLE
After removing and re-adding plugin, DeviceReady won't fire

### ISSUE THREAD

**Issue by ragcsalo** [apache/cordova-plugin-dialogs#173]
I'm developing an app on iOS.
I have removed the 2.0.2 version of the plugin then re-installed it from this repo. The app didn't start, the DeviceReady event never fired. Then I've removed the plugin and added v2.0.2 again but the same problem persists.
The problem exists on any real iOS device and also in the simulator. PLEASE HELP!!!! :-/

**Comment by jcesarmobile** [comment]
can you provide a sample app?

**Comment by jcesarmobile** [comment]
closing as no sample app was provided
