### ISSUE TITLE
the latest version 2.0.2 is missing methods listed in the current latest version

### ISSUE THREAD

**Issue by miguelperez** [apache/cordova-plugin-dialogs#180]
# Bug Report

## Problem
It looks like a new version including newest methods is missing on NPM.

### What is expected to happen?
The docs on the readme should work properly, the documentation on the website is ahead of what is actually released.

<img width="1044" alt="image" src="https://github.com/user-attachments/assets/1e854a0b-236b-4c17-b64e-dbea0d906e6b">

### What does actually happen?
The plugin code is not up to date.

### Version information

I am using the latest cordova version. 12.x

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by jcesarmobile** [comment]
The yellow box with “master” on it means the docs are generated from master branch, which usually includes unreleased changes.

you can install the plugin from the  GitHub url if you want to have latest changes.

`cordova plugin add https://github.com/apache/cordova-plugin-dialogs`
